export const BATCH3 = [
  {
    id: "cardiogen",
    name: "Cardiogen",
    aliases: ["Ala-Glu-Asp-Arg", "Cardiac Bioregulator"],
    category: ["Khavinson Bioregulators", "Longevity"],
    mechanism:
      "Tetrapeptide bioregulator targeting cardiac muscle tissue. Developed by Prof. Vladimir Khavinson at the St. Petersburg Institute of Bioregulation. Research suggests epigenetic regulation of cardiomyocyte gene expression, improving cardiac efficiency and longevity.",
    halfLife: "Hours",
    reconstitution: { solvent: "Bacteriostatic Water", typicalVialMg: 20, typicalVolumeMl: 1 },
    dosingRange: { low: "5mg", medium: "10mg", high: "20mg", frequency: "Daily x 10-day course, 1-2x/year" },
    tags: ["heart", "cardiac", "bioregulator", "Khavinson", "longevity", "epigenetic", "cardiomyocyte"],
    sourcingNotes: "Swiss Chems carries 20mg. Russian bioregulator — course dosed. Part of Khavinson's organ-specific peptide bioregulator series.",
    warnings: ["Course dosing — not continuous", "Limited Western clinical data", "Stack with Epitalon for comprehensive longevity protocol"],
    tier: "pro",
  },
  {
    id: "vilon",
    name: "Vilon",
    aliases: ["Lys-Glu", "Immune-Neuroendocrine Bioregulator"],
    category: ["Khavinson Bioregulators", "Immune"],
    mechanism:
      "Dipeptide bioregulator (Lys-Glu). Targets immune and neuroendocrine systems. Research shows restoration of immune function, particularly in aging models. One of the simplest Khavinson peptides by structure but robust data for immune normalization.",
    halfLife: "Hours",
    reconstitution: { solvent: "Bacteriostatic Water", typicalVialMg: 20, typicalVolumeMl: 1 },
    dosingRange: { low: "5mg", medium: "10mg", high: "20mg", frequency: "Daily x 10-day course" },
    tags: ["immune", "neuroendocrine", "bioregulator", "Khavinson", "longevity", "dipeptide"],
    sourcingNotes: "Swiss Chems carries 20mg. Dipeptide structure makes it one of the most stable Khavinson bioregulators.",
    warnings: ["Course dosing — not continuous", "May modulate immune response — caution with autoimmune conditions"],
    tier: "pro",
  },
  {
    id: "livagen",
    name: "Livagen",
    aliases: ["Liver Bioregulator", "Ala-Glu-Asp-Pro"],
    category: ["Khavinson Bioregulators", "Longevity"],
    mechanism:
      "Tetrapeptide liver bioregulator. Research focuses on hepatocyte gene expression, liver detoxification pathway support, and genoprotective effects. May support chromatin decondensation and gene activity restoration in aging liver tissue.",
    halfLife: "Hours",
    reconstitution: { solvent: "Bacteriostatic Water", typicalVialMg: 20, typicalVolumeMl: 1 },
    dosingRange: { low: "5mg", medium: "10mg", high: "20mg", frequency: "Daily x 10-day course" },
    tags: ["liver", "hepatic", "detox", "bioregulator", "Khavinson", "longevity", "genoprotective"],
    sourcingNotes: "Swiss Chems carries 20mg. Relevant for anyone running aggressive stacks with hepatic load concerns.",
    warnings: ["Course dosing — not continuous", "Not a replacement for liver support supplements like TUDCA/NAC"],
    tier: "pro",
  },
  {
    id: "bronchogen",
    name: "Bronchogen",
    aliases: ["Ala-Glu-Asp-Leu", "Bronchial Bioregulator"],
    category: ["Khavinson Bioregulators", "Longevity"],
    mechanism:
      "Tetrapeptide targeting bronchial and lung epithelial tissue. Research shows restoration of bronchial mucosal function, anti-inflammatory properties in airway tissue, and potential benefit in chronic respiratory conditions.",
    halfLife: "Hours",
    reconstitution: { solvent: "Bacteriostatic Water", typicalVialMg: 20, typicalVolumeMl: 1 },
    dosingRange: { low: "5mg", medium: "10mg", high: "20mg", frequency: "Daily x 10-day course" },
    tags: ["lung", "bronchial", "respiratory", "bioregulator", "Khavinson", "longevity", "airway"],
    sourcingNotes: "Swiss Chems carries 20mg. Research interest in COPD, asthma, and respiratory aging models.",
    warnings: ["Course dosing — not continuous", "Limited human clinical data"],
    tier: "pro",
  },
  {
    id: "cortagen",
    name: "Cortagen",
    aliases: ["Ala-Glu-Asp-Pro", "Neural Bioregulator"],
    category: ["Khavinson Bioregulators", "Nootropic"],
    mechanism:
      "Tetrapeptide bioregulator targeting neural and cortical tissue. Research suggests neuroprotective and neurorestorative effects via gene expression regulation in cortical neurons. May support cognitive function and neural tissue longevity.",
    halfLife: "Hours",
    reconstitution: { solvent: "Bacteriostatic Water", typicalVialMg: 20, typicalVolumeMl: 1 },
    dosingRange: { low: "5mg", medium: "10mg", high: "20mg", frequency: "Daily x 10-day course" },
    tags: ["brain", "neural", "neuroprotective", "bioregulator", "Khavinson", "longevity", "cortical"],
    sourcingNotes: "Swiss Chems carries 20mg. Natural pair with Pinealon for CNS longevity protocol.",
    warnings: ["Course dosing — not continuous", "Limited human data — primarily animal models"],
    tier: "pro",
  },
  {
    id: "thymogen",
    name: "Thymogen",
    aliases: ["Glu-Trp", "Thymic Dipeptide"],
    category: ["Khavinson Bioregulators", "Immune"],
    mechanism:
      "Dipeptide (Glu-Trp) thymic bioregulator. Distinct from Thymalin — Thymogen is a smaller dipeptide with documented immunomodulatory effects, T-cell differentiation support, and anti-aging thymic activity. Approved drug in Russia for immune deficiency.",
    halfLife: "Hours",
    reconstitution: { solvent: "Bacteriostatic Water", typicalVialMg: 20, typicalVolumeMl: 1 },
    dosingRange: { low: "5mg", medium: "10mg", high: "20mg", frequency: "Daily x 10-day course" },
    tags: ["immune", "thymus", "T-cell", "bioregulator", "Khavinson", "longevity", "dipeptide"],
    sourcingNotes: "Swiss Chems carries 20mg. Approved pharmaceutical in Russia. Distinct from Thymalin — different structure, similar target organ.",
    warnings: ["Course dosing — not continuous", "May interact with immunosuppressive therapy"],
    tier: "pro",
  },
  {
    id: "vesilute",
    name: "Vesilute",
    aliases: ["Vascular Bioregulator"],
    category: ["Khavinson Bioregulators", "Longevity"],
    mechanism:
      "Khavinson peptide bioregulator targeting vascular endothelial tissue. Research focus on endothelial cell gene expression regulation, vascular wall integrity, and anti-aging effects in the cardiovascular system.",
    halfLife: "Hours",
    reconstitution: { solvent: "Bacteriostatic Water", typicalVialMg: 20, typicalVolumeMl: 1 },
    dosingRange: { low: "5mg", medium: "10mg", high: "20mg", frequency: "Daily x 10-day course" },
    tags: ["vascular", "endothelial", "cardiovascular", "bioregulator", "Khavinson", "longevity"],
    sourcingNotes: "Swiss Chems carries 20mg. Cardiovascular longevity focus — relevant for Lp(a) and endothelial health concerns.",
    warnings: ["Course dosing — not continuous", "Limited English-language clinical data — primarily Russian literature"],
    tier: "pro",
  },
  {
    id: "ovagen",
    name: "Ovagen",
    aliases: ["Liver-Ovary Bioregulator"],
    category: ["Khavinson Bioregulators", "Longevity"],
    mechanism:
      "Khavinson peptide bioregulator with dual liver and ovarian tissue targeting. Research suggests hepatocyte and ovarian cell gene expression regulation. Used in female longevity protocols and fertility research.",
    halfLife: "Hours",
    reconstitution: { solvent: "Bacteriostatic Water", typicalVialMg: 20, typicalVolumeMl: 1 },
    dosingRange: { low: "5mg", medium: "10mg", high: "20mg", frequency: "Daily x 10-day course" },
    tags: ["liver", "ovary", "female", "bioregulator", "Khavinson", "longevity", "fertility"],
    sourcingNotes: "Swiss Chems carries 20mg. Primarily female longevity protocol use, though liver effects are gender-neutral.",
    warnings: ["Course dosing — not continuous", "Limited data in males"],
    tier: "pro",
  },
  {
    id: "pancragen",
    name: "Pancragen",
    aliases: ["Pancreatic Bioregulator", "Ala-Glu-Asp-Pro"],
    category: ["Khavinson Bioregulators", "GLP / Metabolic"],
    mechanism:
      "Tetrapeptide pancreatic bioregulator. Targets pancreatic exocrine and endocrine cells. Research shows restoration of insulin secretion patterns and pancreatic tissue gene expression in aging and diabetic models. Relevant for metabolic protocol support.",
    halfLife: "Hours",
    reconstitution: { solvent: "Bacteriostatic Water", typicalVialMg: 20, typicalVolumeMl: 1 },
    dosingRange: { low: "5mg", medium: "10mg", high: "20mg", frequency: "Daily x 10-day course" },
    tags: ["pancreas", "insulin", "metabolic", "bioregulator", "Khavinson", "longevity", "diabetes"],
    sourcingNotes: "Swiss Chems carries 20mg. Logical stack companion to GLP-1 agents for comprehensive metabolic longevity.",
    warnings: ["Course dosing — not continuous", "Monitor blood glucose if running alongside GLP-1 agents"],
    tier: "pro",
  },
  {
    id: "chonluten",
    name: "Chonluten",
    aliases: ["Colon Bioregulator", "Gly-Glu-Pro"],
    category: ["Khavinson Bioregulators", "Healing / Recovery"],
    mechanism:
      "Tripeptide (Gly-Glu-Pro) bioregulator targeting colon and intestinal epithelial cells. Research shows restoration of intestinal mucosa gene expression, anti-inflammatory effects in the gut, and potential benefit in inflammatory bowel conditions.",
    halfLife: "Hours",
    reconstitution: { solvent: "Bacteriostatic Water or oral", typicalVialMg: 20, typicalVolumeMl: 1 },
    dosingRange: { low: "5mg", medium: "10mg", high: "20mg", frequency: "Daily x 10-day course" },
    tags: ["gut", "colon", "intestinal", "IBD", "bioregulator", "Khavinson", "longevity", "anti-inflammatory"],
    sourcingNotes: "Swiss Chems carries 20mg. Natural complement to KPV and BPC-157 for gut healing protocols.",
    warnings: ["Course dosing — not continuous", "Oral route viable for gut-targeted delivery"],
    tier: "pro",
  },
  {
    id: "prostamax",
    name: "Prostamax",
    aliases: ["Prostate Bioregulator"],
    category: ["Khavinson Bioregulators", "Longevity"],
    mechanism:
      "Khavinson peptide bioregulator targeting prostate gland tissue. Research focuses on prostatic epithelial cell gene expression, anti-inflammatory action in prostate tissue, and BPH-related research models. Relevant for male longevity protocols.",
    halfLife: "Hours",
    reconstitution: { solvent: "Bacteriostatic Water", typicalVialMg: 20, typicalVolumeMl: 1 },
    dosingRange: { low: "5mg", medium: "10mg", high: "20mg", frequency: "Daily x 10-day course" },
    tags: ["prostate", "BPH", "male", "bioregulator", "Khavinson", "longevity", "anti-inflammatory"],
    sourcingNotes: "Swiss Chems carries 20mg. Relevant complement to retatrutide/TRT protocols given prostate health considerations.",
    warnings: ["Course dosing — not continuous", "Not a treatment for prostate cancer — research context only"],
    tier: "pro",
  },
  {
    id: "cartalax",
    name: "Cartalax",
    aliases: ["Cartilage Bioregulator", "Ala-Glu-Asp-Arg"],
    category: ["Khavinson Bioregulators", "Healing / Recovery"],
    mechanism:
      "Tetrapeptide bioregulator targeting cartilage and connective tissue. Research shows chondrocyte gene expression regulation, anti-inflammatory effects in joint tissue, and potential benefit in osteoarthritis models.",
    halfLife: "Hours",
    reconstitution: { solvent: "Bacteriostatic Water", typicalVialMg: 20, typicalVolumeMl: 1 },
    dosingRange: { low: "5mg", medium: "10mg", high: "20mg", frequency: "Daily x 10-day course" },
    tags: ["cartilage", "joint", "connective tissue", "chondrocyte", "bioregulator", "Khavinson", "osteoarthritis"],
    sourcingNotes: "Swiss Chems carries 20mg. Logical stack companion to BPC-157 and TB-500 for joint recovery protocols.",
    warnings: [
      "Course dosing — not continuous",
      "Not a substitute for BPC-157/TB-500 in acute injury — Cartalax is longer-term maintenance",
    ],
    tier: "pro",
  },
  {
    id: "testagen",
    name: "Testagen",
    aliases: ["Testicular Bioregulator", "Ala-Glu-Asp-Gly"],
    category: ["Testosterone Support"],
    mechanism:
      "Tetrapeptide bioregulator targeting testicular tissue. Research shows restoration of Leydig cell and Sertoli cell gene expression. Potential benefit for age-related testosterone decline, fertility, and testicular function maintenance — particularly relevant during TRT protocols.",
    halfLife: "Hours",
    reconstitution: { solvent: "Bacteriostatic Water", typicalVialMg: 20, typicalVolumeMl: 1 },
    dosingRange: { low: "5mg", medium: "10mg", high: "20mg", frequency: "Daily x 10-day course" },
    tags: ["testes", "testosterone", "fertility", "Leydig cell", "bioregulator", "Khavinson", "TRT", "longevity"],
    sourcingNotes: "Swiss Chems carries 20mg. Relevant for men on TRT wanting to maintain testicular function alongside Gonadorelin/HCG.",
    warnings: ["Course dosing — not continuous", "Not a replacement for HCG or Gonadorelin for testicular preservation on TRT"],
    tier: "pro",
  },
];
