export const BATCH5 = [
  {
    id: "mk-677",
    name: "MK-677 (Ibutamoren)",
    aliases: ["Ibutamoren", "Nutrobal", "MK677"],
    category: ["SARMs", "GH Peptides"],
    mechanism:
      "Oral ghrelin receptor agonist (not technically a SARM). Stimulates GH and IGF-1 secretion without affecting cortisol. Oral GH secretagogue — only option for oral GH axis stimulation. Significantly increases appetite. 24-hour half-life enables once-daily dosing.",
    halfLife: "~24 hours",
    reconstitution: { solvent: "Oral capsule", typicalVialMg: null, typicalVolumeMl: null },
    dosingRange: { low: "10mg", medium: "20mg", high: "25mg", frequency: "Daily oral, pre-sleep" },
    tags: ["GH", "IGF-1", "oral", "ghrelin", "muscle", "anti-aging", "appetite", "secretagogue"],
    sourcingNotes: "Swiss Chems carries 60-cap bottles. One of the most popular compounds on the platform. Best taken pre-sleep to align with natural GH pulse.",
    warnings: [
      "Significant appetite increase — manage caloric intake",
      "Water retention common",
      "May worsen insulin sensitivity — monitor fasting glucose",
      "Long-term use caution — sustained IGF-1 elevation",
    ],
    tier: "pro",
  },
  {
    id: "rad-140",
    name: "RAD-140 (Testolone)",
    aliases: ["Testolone", "RAD140"],
    category: ["SARMs"],
    mechanism:
      "Highly selective androgen receptor modulator. High anabolic:androgenic ratio (~90:1). Activates AR in muscle and bone with minimal prostate/DHT-pathway activity. Neuroprotective via AR activation in the brain — reduces amyloid-beta toxicity in preclinical models.",
    halfLife: "~60 hours",
    reconstitution: { solvent: "Oral capsule", typicalVialMg: null, typicalVolumeMl: null },
    dosingRange: { low: "5mg", medium: "10mg", high: "20mg", frequency: "Daily oral" },
    tags: ["SARM", "anabolic", "muscle", "androgen receptor", "neuroprotective", "lean mass"],
    sourcingNotes: "Swiss Chems carries. One of the most potent SARMs — suppressive at higher doses. PCT consideration required.",
    warnings: [
      "Testosterone suppression — PCT required post-cycle",
      "Liver enzyme elevation reported",
      "Not for use without baseline labs",
      "Phase 1 trials paused due to hepatotoxicity signals",
    ],
    tier: "elite",
  },
  {
    id: "gw-501516",
    name: "GW-501516 (Cardarine)",
    aliases: ["Cardarine", "GW501516", "Endurobol"],
    category: ["SARMs", "GLP / Metabolic"],
    mechanism:
      "PPARδ (Peroxisome proliferator-activated receptor delta) agonist. Not technically a SARM — activates fatty acid oxidation pathways, dramatically increases endurance and exercise capacity, and shifts metabolism toward fat burning. No androgen receptor activity.",
    halfLife: "~16-24 hours",
    reconstitution: { solvent: "Oral capsule", typicalVialMg: null, typicalVolumeMl: null },
    dosingRange: { low: "5mg", medium: "10mg", high: "20mg", frequency: "Daily oral" },
    tags: ["PPAR", "endurance", "fat oxidation", "metabolic", "cardio", "exercise mimetic"],
    sourcingNotes:
      "Swiss Chems carries. Development halted by GSK after carcinogenicity signals in animal studies. Community use continues — significant risk awareness required.",
    warnings: [
      "⚠️ CANCER RISK: Development halted due to dose-dependent tumor promotion in animal studies",
      "No human safety data",
      "Risk-benefit ratio is individual decision — informed use only",
      "Do not use long-term",
    ],
    tier: "goat",
  },
  {
    id: "yk-11",
    name: "YK-11",
    aliases: ["YK11"],
    category: ["SARMs"],
    mechanism:
      "Steroidal SARM and myostatin inhibitor. Binds AR and also inhibits myostatin expression in muscle cells via Follistatin upregulation. Dual mechanism: anabolic AR activation + myostatin suppression. One of the most potent SARMs by lean mass impact.",
    halfLife: "~6-10 hours",
    reconstitution: { solvent: "Oral capsule", typicalVialMg: null, typicalVolumeMl: null },
    dosingRange: { low: "2.5mg", medium: "5mg", high: "10mg", frequency: "Daily (split dose due to half-life)" },
    tags: ["SARM", "myostatin", "anabolic", "androgen receptor", "lean mass", "follistatin"],
    sourcingNotes: "Swiss Chems carries. Steroidal backbone — behaves more like a steroid than non-steroidal SARMs. Most suppressive SARM on the list.",
    warnings: [
      "Most suppressive SARM listed — PCT required",
      "Liver stress likely — cycle short",
      "Steroidal backbone — more systemic than non-steroidal SARMs",
      "Limited human data",
    ],
    tier: "goat",
  },
  {
    id: "s4",
    name: "S4 (Andarine)",
    aliases: ["Andarine", "GTx-007"],
    category: ["SARMs"],
    mechanism:
      "Partial androgen receptor agonist. Strong affinity for muscle and bone AR. Notable for hardening and vascularity effects. Yellow vision tint (temporary) is dose-dependent and the primary side effect — caused by binding to ocular AR.",
    halfLife: "~3-4 hours",
    reconstitution: { solvent: "Oral capsule", typicalVialMg: null, typicalVolumeMl: null },
    dosingRange: { low: "12.5mg", medium: "25mg", high: "50mg", frequency: "Daily oral (split dose)" },
    tags: ["SARM", "anabolic", "hardening", "vascularity", "androgen receptor", "lean mass"],
    sourcingNotes: "Swiss Chems carries. Split dosing (AM/PM) due to short half-life. Yellow vision tint at >50mg typically resolves off-cycle.",
    warnings: ["Yellow/green vision tint at higher doses — dose-dependent, reversible", "Testosterone suppression — PCT consideration", "Short half-life requires split dosing"],
    tier: "elite",
  },
  {
    id: "s23",
    name: "S-23",
    aliases: ["S23"],
    category: ["SARMs"],
    mechanism:
      "High-affinity, non-steroidal SARM. Among the most potent by AR binding affinity. Strong anabolic effects in muscle and bone. Significantly suppresses FSH/LH — studied as a male contraceptive. Dramatic lean mass increases in research models.",
    halfLife: "~12 hours",
    reconstitution: { solvent: "Oral capsule", typicalVialMg: null, typicalVolumeMl: null },
    dosingRange: { low: "5mg", medium: "10mg", high: "20mg", frequency: "Daily oral" },
    tags: ["SARM", "anabolic", "high affinity", "lean mass", "androgen receptor", "contraceptive"],
    sourcingNotes: "Swiss Chems carries. Most potent non-steroidal SARM. Studied as male contraceptive — complete spermatogenesis suppression at research doses.",
    warnings: [
      "Most potent SARM on platform — full PCT required",
      "Complete testosterone/sperm suppression at higher doses",
      "Do not use if trying to conceive",
      "Liver monitoring recommended",
    ],
    tier: "goat",
  },
  {
    id: "rad-150",
    name: "RAD-150 (TLB-150)",
    aliases: ["TLB-150", "Esterified RAD-140"],
    category: ["SARMs"],
    mechanism:
      "Benzoate ester prodrug of RAD-140. Esterification extends half-life and provides more stable blood levels than RAD-140. Cleaves in plasma to deliver RAD-140. Same AR selectivity and anabolic:androgenic ratio as parent compound with smoother pharmacokinetic profile.",
    halfLife: "~48-72 hours (ester prolongs vs ~60hr RAD-140)",
    reconstitution: { solvent: "Oral capsule", typicalVialMg: null, typicalVolumeMl: null },
    dosingRange: { low: "5mg", medium: "10mg", high: "15mg", frequency: "Daily oral" },
    tags: ["SARM", "anabolic", "ester", "prodrug", "androgen receptor", "lean mass"],
    sourcingNotes: "Swiss Chems carries. Newer compound — less data than RAD-140 but same mechanism with extended half-life advantage.",
    warnings: ["Same warnings as RAD-140", "Ester cleavage variability between individuals", "Even less long-term data than RAD-140"],
    tier: "elite",
    variantOf: "rad-140",
    variantNote: "Esterified prodrug of RAD-140. More stable blood levels, extended half-life. Otherwise same mechanism and precautions.",
  },
  {
    id: "sr-9011",
    name: "SR-9011",
    aliases: ["Rev-Erb Agonist", "SR9011"],
    category: ["SARMs", "Longevity"],
    mechanism:
      "Rev-Erb α/β nuclear receptor agonist. Modulates circadian rhythm machinery at the molecular level. Increases metabolic rate, reduces fat mass, improves endurance, and normalizes disrupted circadian gene expression. SLU-PP-332 targets the same receptor. Not an androgen receptor compound — different mechanism than other SARMs.",
    halfLife: "~4 hours (short — split dosing)",
    reconstitution: { solvent: "Oral capsule", typicalVialMg: null, typicalVolumeMl: null },
    dosingRange: { low: "10mg", medium: "20mg", high: "30mg", frequency: "Daily oral (split AM/PM)" },
    tags: ["circadian", "Rev-Erb", "metabolic", "fat loss", "endurance", "exercise mimetic", "longevity"],
    sourcingNotes:
      "Swiss Chems carries. Not androgenic — no suppression. Circadian biology mechanism makes it relevant for shift workers and those with disrupted sleep schedules.",
    warnings: ["Not a SARM in the traditional androgen receptor sense — categorized here for catalog organization only", "Short half-life requires split dosing", "Limited human data"],
    tier: "pro",
  },
  {
    id: "ac-262",
    name: "AC-262 (Accadrine)",
    aliases: ["AC-262536", "Accadrine"],
    category: ["SARMs"],
    mechanism:
      "Partial androgen receptor agonist. Moderate selectivity — weaker than RAD-140 or S-23 but cleaner side effect profile. Research focus on muscle and bone with reduced prostate stimulation. More conservative entry-level SARM profile.",
    halfLife: "~6 hours",
    reconstitution: { solvent: "Oral capsule", typicalVialMg: null, typicalVolumeMl: null },
    dosingRange: { low: "10mg", medium: "30mg", high: "50mg", frequency: "Daily oral" },
    tags: ["SARM", "partial agonist", "anabolic", "androgen receptor", "muscle", "bone"],
    sourcingNotes: "Swiss Chems carries. One of the more conservative SARMs — appropriate starting point for those new to androgen receptor modulators.",
    warnings: ["Testosterone suppression still occurs — monitor", "Less characterized than RAD-140 or Ostarine", "PCT consideration"],
    tier: "elite",
  },
  {
    id: "slu-pp-332",
    name: "SLU-PP-332",
    aliases: ["SLU PP 332", "Exercise Mimetic"],
    category: ["SARMs", "GLP / Metabolic"],
    mechanism:
      "Pan-ERR (Estrogen-Related Receptor) agonist. Activates ERRα, ERRβ, and ERRγ — transcription factors regulating mitochondrial biogenesis and oxidative metabolism. Animal studies show dramatic endurance improvement (running distance +70%), fat loss, and cardiac protection. True 'exercise in a pill' mechanism.",
    halfLife: "Unknown — short likely",
    reconstitution: { solvent: "Oral capsule", typicalVialMg: null, typicalVolumeMl: null },
    dosingRange: { low: "25mg", medium: "50mg", high: "100mg", frequency: "Daily oral" },
    tags: ["ERR", "exercise mimetic", "endurance", "mitochondrial biogenesis", "fat loss", "metabolic", "cardiac"],
    sourcingNotes: "Swiss Chems carries. Very early research compound — animal data only. ERR mechanism is highly novel. Not androgenic.",
    warnings: [
      "No human data — animal studies only",
      "Long-term ERR agonism effects unknown",
      "Not androgenic — no PCT needed but mechanism has systemic transcriptional effects",
    ],
    tier: "goat",
  },
];
