export const BATCH6 = [
  {
    id: "exemestane",
    name: "Exemestane",
    aliases: ["Aromasin", "Steroidal AI"],
    category: ["Estrogen Control"],
    mechanism:
      "Steroidal aromatase inhibitor (Type I). Suicide inhibitor — permanently inactivates the aromatase enzyme it binds to. New enzyme synthesis required before aromatase activity returns. More durable estrogen suppression than non-steroidal AIs. Preferred over letrozole for TRT protocols due to lower rebound risk.",
    halfLife: "~27 hours",
    reconstitution: { solvent: "Oral tablet", typicalVialMg: null, typicalVolumeMl: null },
    dosingRange: { low: "12.5mg", medium: "25mg", high: "25mg", frequency: "Every other day to twice weekly" },
    tags: ["aromatase inhibitor", "estrogen control", "TRT", "AI", "steroidal", "suicide inhibitor", "protocol support"],
    sourcingNotes: "Widely available pharmaceutical. Dan's recommendation over letrozole for TRT support due to steroidal mechanism and lower rebound risk.",
    warnings: ["Estrogen crash risk — do not over-use", "Joint pain and libido reduction with excessive suppression", "Monitor E2 labs before adjusting dose", "Steroidal structure — mild androgenic activity possible"],
    tier: "pro",
  },
  {
    id: "anastrozole",
    name: "Anastrozole",
    aliases: ["Arimidex", "Non-steroidal AI"],
    category: ["Estrogen Control"],
    mechanism:
      "Non-steroidal aromatase inhibitor (Type II). Reversible competitive inhibitor — aromatase activity returns when drug clears. Most commonly prescribed AI for TRT estrogen management. Effective but rebound risk higher than exemestane upon cessation.",
    halfLife: "~46 hours",
    reconstitution: { solvent: "Oral tablet", typicalVialMg: null, typicalVolumeMl: null },
    dosingRange: { low: "0.25mg", medium: "0.5mg", high: "1mg", frequency: "Every other day to twice weekly" },
    tags: ["aromatase inhibitor", "estrogen control", "TRT", "AI", "non-steroidal", "protocol support"],
    sourcingNotes: "Most widely prescribed TRT ancillary. Reversible mechanism — less durable than exemestane but easier to dial in.",
    warnings: ["Estrogen rebound upon discontinuation", "Bone density loss with long-term use/excess suppression", "Monitor E2 labs — over-suppression is common mistake"],
    tier: "pro",
  },
  {
    id: "letrozole",
    name: "Letrozole",
    aliases: ["Femara", "Nuclear AI"],
    category: ["Estrogen Control"],
    mechanism:
      "Non-steroidal aromatase inhibitor. Most potent AI available — suppresses estrogen production up to 98%. Used for gynecomastia reversal (short course) and extreme estrogen management. Generally too potent for routine TRT use.",
    halfLife: "~48 hours",
    reconstitution: { solvent: "Oral capsule", typicalVialMg: null, typicalVolumeMl: null },
    dosingRange: { low: "0.5mg", medium: "1mg", high: "2.5mg", frequency: "Every other day (cycle use) or daily (gyno reversal)" },
    tags: ["aromatase inhibitor", "estrogen control", "gynecomastia", "AI", "potent", "protocol support"],
    sourcingNotes: "Swiss Chems carries. Reserved for gyno reversal protocols or situations where anastrozole/exemestane insufficient. Excessive use is easy — E2 crash happens fast.",
    warnings: [
      "⚠️ MOST POTENT AI — easy to crash estrogen completely",
      "Bone density, lipid profile, joint health, libido all suffer with over-suppression",
      "Use for short courses only unless directed by physician",
      "Lab monitoring essential",
    ],
    tier: "elite",
  },
  {
    id: "enclomiphene",
    name: "Enclomiphene",
    aliases: ["Androxal", "Trans-clomiphene"],
    category: ["Estrogen Control"],
    mechanism:
      "Pure trans-isomer of clomiphene. Selective estrogen receptor modulator (SERM) at the hypothalamus/pituitary — blocks estrogen negative feedback, increasing LH and FSH output, which stimulates endogenous testosterone production. Maintains spermatogenesis and testicular volume unlike exogenous testosterone.",
    halfLife: "~10-13 hours",
    reconstitution: { solvent: "Oral capsule", typicalVialMg: null, typicalVolumeMl: null },
    dosingRange: { low: "12.5mg", medium: "25mg", high: "50mg", frequency: "Daily oral" },
    tags: ["SERM", "testosterone", "fertility", "LH", "FSH", "natty", "HPG axis", "protocol support"],
    sourcingNotes: "Swiss Chems carries. Preferred over full clomiphene for natty testosterone support — pure trans isomer avoids cis-isomer's estrogenic/visual side effects.",
    warnings: ["Visual disturbances possible (less than full clomiphene)", "Not effective if primary hypogonadism (testes issue vs pituitary)", "Labs required to verify LH/FSH response"],
    tier: "pro",
  },
  {
    id: "clomiphene",
    name: "Clomiphene",
    aliases: ["Clomid", "Clomifene", "50/50 isomer"],
    category: ["Estrogen Control"],
    mechanism:
      "Mixed cis/trans SERM. Trans-isomer (enclomiphene) drives LH/FSH increase; cis-isomer (zuclomiphene) has estrogenic effects and longer half-life. Classic PCT compound post-anabolic cycle. Effective for HPG axis restart and fertility.",
    halfLife: "~5-7 days (zuclomiphene component accumulates)",
    reconstitution: { solvent: "Oral capsule", typicalVialMg: null, typicalVolumeMl: null },
    dosingRange: { low: "25mg", medium: "50mg", high: "100mg", frequency: "Daily oral (PCT: 4-6 weeks)" },
    tags: ["SERM", "PCT", "testosterone", "fertility", "LH", "FSH", "HPG restart", "protocol support"],
    sourcingNotes: "Swiss Chems carries. Classic PCT choice. Enclomiphene preferred for TRT support — clomiphene better for full PCT restart.",
    warnings: ["Visual disturbances (blurred vision, floaters) — stop if occurs", "Mood swings from mixed isomer estrogenic activity", "Not for long-term continuous use"],
    tier: "pro",
  },
  {
    id: "tamoxifen",
    name: "Tamoxifen",
    aliases: ["Nolvadex", "TAM"],
    category: ["Estrogen Control"],
    mechanism:
      "SERM with tissue-selective estrogen effects. Antagonist at breast/pituitary ER — used for gynecomastia prevention and PCT. Agonist at bone and liver ER. Stimulates LH/FSH for HPG restart. Often used alongside clomiphene in PCT protocols.",
    halfLife: "~5-7 days",
    reconstitution: { solvent: "Oral tablet", typicalVialMg: null, typicalVolumeMl: null },
    dosingRange: { low: "10mg", medium: "20mg", high: "40mg", frequency: "Daily oral (PCT: 4-6 weeks)" },
    tags: ["SERM", "PCT", "gynecomastia", "estrogen", "LH", "FSH", "protocol support", "breast tissue"],
    sourcingNotes: "Widely available pharmaceutical. Standard PCT compound. Often stacked with clomiphene: Tamox 20mg + Clomid 50mg.",
    warnings: ["Blood clot risk (DVT) — particularly at higher doses or combined with other risk factors", "May reduce IGF-1 levels — consideration for GH protocol users", "Liver enzyme elevation possible"],
    tier: "pro",
  },
  {
    id: "dim",
    name: "DIM",
    aliases: ["Diindolylmethane", "DIM-E", "3,3'-Diindolylmethane"],
    category: ["Estrogen Control"],
    mechanism:
      "Cruciferous vegetable metabolite. Shifts estrogen metabolism toward the less potent 2-hydroxyestrone pathway (vs 16-hydroxyestrone). Reduces total estrogen load and improves estrogen metabolite profile. Used alongside AIs for comprehensive estrogen management.",
    halfLife: "~8-12 hours",
    reconstitution: { solvent: "Oral capsule (enhanced bioavailability forms preferred)", typicalVialMg: null, typicalVolumeMl: null },
    dosingRange: { low: "100mg", medium: "200mg", high: "400mg", frequency: "Daily oral with food" },
    tags: ["estrogen", "metabolism", "2-OH pathway", "protocol support", "AI complement", "cruciferous"],
    sourcingNotes:
      "Supplement category — Codeage DIM-E (enhanced bioavailability with BioPerine) is Dan's preferred source. Not a peptide but essential protocol support compound.",
    warnings: [
      "Enhanced absorption forms (DIM-E, BioPerine) significantly outperform standard DIM",
      "May compete with AI — monitor E2 labs when combining",
      "Reduces estrogen — do not combine with estrogen-sensitive medications without physician oversight",
    ],
    tier: "entry",
  },
  {
    id: "calcium-d-glucarate",
    name: "Calcium-D-Glucarate",
    aliases: ["CDG", "Calcium Glucarate"],
    category: ["Estrogen Control"],
    mechanism:
      "Inhibits β-glucuronidase enzyme in the gut. β-glucuronidase enables enterohepatic recirculation of conjugated estrogens — they get deconjugated and re-absorbed. CDG blocks this loop, ensuring estrogen metabolites are excreted rather than recycled. Complements liver-based estrogen clearance.",
    halfLife: "~8 hours",
    reconstitution: { solvent: "Oral capsule", typicalVialMg: null, typicalVolumeMl: null },
    dosingRange: { low: "500mg", medium: "1000mg", high: "1500mg", frequency: "Daily oral with meals" },
    tags: ["estrogen", "detox", "enterohepatic", "glucuronidation", "protocol support", "liver", "gut"],
    sourcingNotes: "Supplement category. Widely available. Logical addition to any estrogen management protocol — closes the enterohepatic loop that AIs miss.",
    warnings: ["May also reduce clearance of other glucuronidated drugs — check interactions", "Less impact if gut microbiome is healthy (less β-glucuronidase activity)"],
    tier: "entry",
  },
  {
    id: "liothyronine-t3",
    name: "Liothyronine T3",
    aliases: ["Cytomel", "Triiodothyronine"],
    category: ["Thyroid Support"],
    mechanism:
      "Active thyroid hormone. T3 directly activates thyroid receptors — increases basal metabolic rate, protein synthesis, fat oxidation, and thermogenesis. Used in cutting phases and for hypothyroid management. Short half-life allows precise dose titration.",
    halfLife: "~2.5 days",
    reconstitution: { solvent: "Oral tablet/capsule", typicalVialMg: null, typicalVolumeMl: null },
    dosingRange: { low: "12.5mcg", medium: "25mcg", high: "50mcg", frequency: "Daily oral (split dose)" },
    tags: ["thyroid", "metabolic rate", "fat loss", "T3", "thermogenesis", "protocol support", "cutting"],
    sourcingNotes: "Swiss Chems carries. Used in cutting protocols — typically 4-8 week cycles. Taper off rather than stopping abruptly.",
    warnings: [
      "Suppresses endogenous thyroid production — taper off slowly",
      "Cardiac risk at high doses — heart rate and blood pressure monitoring",
      "Muscle catabolism at high doses — adequate protein intake essential",
      "Do not combine with other stimulants without physician oversight",
    ],
    tier: "elite",
  },
  {
    id: "levothyroxine-t4",
    name: "Levothyroxine T4",
    aliases: ["Synthroid", "Thyroxine", "L-T4"],
    category: ["Thyroid Support"],
    mechanism:
      "Thyroid hormone precursor. Converts to active T3 peripherally via deiodinase enzymes. Slower onset and more stable levels than T3. Standard hypothyroidism treatment and used in performance protocols for gentler metabolic support. Conversion efficiency varies by individual.",
    halfLife: "~7 days",
    reconstitution: { solvent: "Oral tablet/capsule", typicalVialMg: null, typicalVolumeMl: null },
    dosingRange: { low: "25mcg", medium: "100mcg", high: "200mcg", frequency: "Daily oral, fasted AM" },
    tags: ["thyroid", "T4", "metabolic", "hypothyroid", "protocol support", "conversion"],
    sourcingNotes: "Swiss Chems carries. Preferred over T3 alone for stable levels. Conversion to T3 varies — poor converters may need T3 addition.",
    warnings: ["Same cardiac and suppression caveats as T3 — slightly more forgiving due to slower conversion", "Take fasted — food and supplements (calcium, iron) reduce absorption", "Labs required to dial in dose"],
    tier: "pro",
  },
  {
    id: "tesofensine",
    name: "Tesofensine",
    aliases: ["NS2330", "Triple Reuptake Inhibitor"],
    category: ["GLP / Metabolic"],
    mechanism:
      "Serotonin, dopamine, and norepinephrine reuptake inhibitor (SNRI+). Originally developed for Parkinson's/Alzheimer's — weight loss observed as major side effect. Among the most potent appetite suppressants in research. Significantly reduces caloric intake via triple monoamine reuptake inhibition.",
    halfLife: "~220 hours (very long — accumulates)",
    reconstitution: { solvent: "Oral capsule", typicalVialMg: null, typicalVolumeMl: null },
    dosingRange: { low: "0.125mg", medium: "0.25mg", high: "0.5mg", frequency: "Daily oral (accumulates — start very low)" },
    tags: ["weight loss", "appetite suppression", "dopamine", "serotonin", "norepinephrine", "metabolic", "reuptake inhibitor"],
    sourcingNotes: "Swiss Chems carries. Extremely long half-life — 10+ day accumulation. Start at absolute minimum dose and wait 2+ weeks before assessing effect.",
    warnings: [
      "⚠️ VERY LONG HALF-LIFE — accumulates over weeks",
      "Blood pressure and heart rate elevation",
      "Insomnia, dry mouth, constipation common",
      "Drug interactions with monoamine system medications",
      "Start at 0.125mg and wait before increasing",
    ],
    tier: "goat",
  },
  {
    id: "mirabegron",
    name: "Mirabegron",
    aliases: ["Myrbetriq", "Beta-3 Agonist"],
    category: ["GLP / Metabolic"],
    mechanism:
      "Selective β3-adrenergic receptor agonist. FDA-approved for overactive bladder. In metabolic context: β3 activation in adipose tissue stimulates brown adipose tissue (BAT) thermogenesis, increasing energy expenditure. Research shows modest but real BAT activation and calorie burning at clinical doses.",
    halfLife: "~50 hours",
    reconstitution: { solvent: "Oral tablet", typicalVialMg: null, typicalVolumeMl: null },
    dosingRange: { low: "25mg", medium: "50mg", high: "100mg", frequency: "Daily oral" },
    tags: ["brown adipose", "BAT", "thermogenesis", "metabolic", "beta-3", "fat loss", "protocol support"],
    sourcingNotes: "Swiss Chems carries. FDA-approved — cleaner safety profile than many metabolic compounds. BAT activation mechanism distinct from other weight loss compounds.",
    warnings: ["Blood pressure elevation at higher doses", "Urinary retention possible", "Drug interactions via CYP2D6"],
    tier: "pro",
  },
  {
    id: "telmisartan",
    name: "Telmisartan",
    aliases: ["Micardis", "ARB / PPARγ"],
    category: ["GLP / Metabolic"],
    mechanism:
      "Angiotensin II receptor blocker (ARB) with unique partial PPARγ agonist activity. ARB mechanism lowers blood pressure and reduces cardiovascular risk. PPARγ activity adds insulin sensitization and metabolic benefits. Research interest in longevity and as alternative to metformin for metabolic optimization.",
    halfLife: "~24 hours",
    reconstitution: { solvent: "Oral tablet", typicalVialMg: null, typicalVolumeMl: null },
    dosingRange: { low: "20mg", medium: "40mg", high: "80mg", frequency: "Daily oral" },
    tags: ["blood pressure", "cardiovascular", "PPARγ", "insulin sensitivity", "metabolic", "longevity", "ARB"],
    sourcingNotes: "Swiss Chems carries. FDA-approved pharmaceutical. Bryan Johnson protocol compound. Particularly relevant for those with cardiovascular concerns alongside peptide protocols.",
    warnings: ["Hypotension risk — monitor BP", "Hyperkalemia risk — avoid with high potassium supplements", "Renal monitoring recommended"],
    tier: "pro",
  },
  {
    id: "oea",
    name: "OEA (Oleoylethanolamide)",
    aliases: ["Oleoylethanolamide", "N-Oleoylethanolamide"],
    category: ["GLP / Metabolic"],
    mechanism:
      "Endogenous lipid signaling molecule produced in the gut after fat consumption. Activates PPARα in intestinal cells, sending satiety signals to the hypothalamus. Reduces food intake and promotes fat oxidation. Produced naturally — OEA supplementation extends this satiety signaling.",
    halfLife: "~4-6 hours",
    reconstitution: { solvent: "Oral — lipid suspension preferred", typicalVialMg: null, typicalVolumeMl: null },
    dosingRange: { low: "100mg", medium: "250mg", high: "500mg", frequency: "30-60 min pre-meal" },
    tags: ["satiety", "appetite", "PPARα", "lipid signaling", "fat oxidation", "metabolic", "gut"],
    sourcingNotes: "Swiss Chems carries. Natural endogenous compound — excellent safety profile. Stack with GLP-1 agents for additive appetite suppression via independent pathway.",
    warnings: ["Take pre-meal for maximal effect", "Fat-soluble — take with fatty foods or MCT oil for absorption"],
    tier: "entry",
  },
  {
    id: "ru58841",
    name: "RU58841",
    aliases: ["RU-58841", "PSK-3841", "Topical Anti-androgen"],
    category: ["Skin / Hair / Nails"],
    mechanism:
      "Non-steroidal topical androgen receptor antagonist. Binds AR in scalp follicles with high affinity, blocking DHT-driven miniaturization. Minimal systemic absorption when applied correctly — acts locally without suppressing systemic androgen levels. Research compound — not approved.",
    halfLife: "Topical — local residence, minimal systemic",
    reconstitution: { solvent: "Ethanol/propylene glycol solution — pre-made or DIY", typicalVialMg: null, typicalVolumeMl: null },
    dosingRange: { low: "25mg", medium: "50mg", high: "75mg", frequency: "Daily topical scalp application" },
    tags: ["hair loss", "DHT", "androgen receptor", "scalp", "topical", "anti-androgen", "alopecia"],
    sourcingNotes:
      "Swiss Chems carries raw powder. Requires preparation in a carrier solution (ethanol + PG or minoxidil base). Popular in hair loss community as alternative to finasteride without systemic effects.",
    warnings: [
      "Raw powder — preparation skill required",
      "Minimal systemic absorption when used correctly — use carrier correctly",
      "Systemic anti-androgen effects possible if overused or carrier is wrong",
      "Research compound — no clinical trial completion",
    ],
    tier: "elite",
  },
];
