/** New catalog rows (raw). Vendor strings stripped at merge via `normalizeNewCatalogEntry`. */
export const BATCH1 = [
  {
    id: "semax",
    name: "Semax",
    aliases: ["ACTH(4-10) analog", "MEHFPGP"],
    category: ["Nootropic"],
    route: ["intranasal", "subQ injection"],
    mechanism:
      "Synthetic ACTH(4-7)-Pro-Gly-Pro fragment. Upregulates BDNF and NGF; neuroprotective. Shorter half-life than N-Acetyl Amidate form. Standard intranasal or subQ research compound.",
    halfLife: "~20 minutes (intranasal active window longer)",
    reconstitution: { solvent: "Bacteriostatic Water", typicalVialMg: 5, typicalVolumeMl: 1 },
    dosingRange: { low: "200mcg", medium: "500mcg", high: "1mg", frequency: "Daily intranasal or subQ" },
    tags: ["nootropic", "BDNF", "NGF", "neuroprotective", "cognitive", "ACTH", "Russian"],
    sourcingNotes:
      "Penguin Peptides carries 5mg and 10mg. For maximum bioavailability and duration, upgrade path is N-Acetyl Semax Amidate.",
    warnings: ["Start low — CNS active compound", "Intranasal preferred for fastest onset"],
    tier: "entry",
    variantOf: "n-acetyl-semax-amidate",
    variantNote: "Base form. Lower cost, shorter acting. N-Acetyl Amidate form is more potent and longer lasting.",
  },
  {
    id: "selank",
    name: "Selank",
    aliases: ["Tuftsin analog", "TP-7"],
    category: ["Nootropic", "Sleep"],
    route: ["subQ injection", "intranasal"],
    mechanism:
      "Synthetic Tuftsin analog (TKPRPGP). Anxiolytic via GABAergic and serotonergic modulation. Immunomodulatory. Enkephalin metabolism regulation. Base form without acetyl/amidate modifications.",
    halfLife: "~2 hours",
    reconstitution: { solvent: "Bacteriostatic Water", typicalVialMg: 5, typicalVolumeMl: 1 },
    dosingRange: { low: "100mcg", medium: "250mcg", high: "500mcg", frequency: "Daily intranasal or subQ" },
    tags: ["nootropic", "anxiolytic", "GABA", "BDNF", "sleep", "anti-anxiety", "immunomodulator"],
    sourcingNotes: "Penguin Peptides carries 5mg and 10mg. Upgrade path is N-Acetyl Selank Amidate for extended activity.",
    warnings: ["Mild sedation possible at higher doses", "Intranasal preferred for CNS delivery"],
    tier: "entry",
    variantOf: "n-acetyl-selank-amidate",
    variantNote: "Base form. More accessible price point. N-Acetyl Amidate form provides longer duration and greater stability.",
  },
  {
    id: "n-acetyl-epitalon-amidate",
    name: "N-Acetyl Epitalon Amidate",
    aliases: ["NA Epitalon Amidate", "Epithalon Amidate"],
    category: ["Longevity"],
    mechanism:
      "Acetylated N-terminus and amidated C-terminus of Epitalon (Ala-Glu-Asp-Gly). Terminal protection reduces enzymatic degradation significantly, extending half-life and bioavailability vs standard Epitalon. Telomerase activation; pineal melatonin regulation; antioxidant.",
    halfLife: "Extended vs standard Epitalon — hours to days",
    reconstitution: { solvent: "Bacteriostatic Water", typicalVialMg: 10, typicalVolumeMl: 1 },
    dosingRange: { low: "1mg", medium: "3mg", high: "5mg", frequency: "Daily x 10-day course, 1-2x/year" },
    tags: ["longevity", "telomere", "anti-aging", "telomerase", "pineal", "antioxidant", "amidate"],
    sourcingNotes: "Specialty vendors — not on Penguin or Swiss Chems. Niche but growing demand. Premium longevity protocol compound.",
    warnings: ["Lower doses required vs standard Epitalon due to enhanced bioavailability", "Course dosing — not continuous"],
    tier: "pro",
    variantOf: "epitalon",
    variantNote: "Premium form. Both termini protected from enzymatic cleavage — significantly more bioavailable and longer acting than standard Epitalon.",
  },
  {
    id: "bpc-157-arginine",
    name: "BPC-157 Arginine Salt",
    aliases: ["BPC-157 Arg", "Stable BPC-157"],
    category: ["Healing / Recovery"],
    mechanism:
      "Arginine salt form of BPC-157 (Body Protection Compound). Claimed higher water solubility and improved stability in solution vs acetate form. Same core mechanism: growth hormone receptor interaction, NO system modulation, angiogenesis, gut and tissue repair.",
    halfLife: "~4-6 hours",
    reconstitution: { solvent: "Bacteriostatic Water", typicalVialMg: 5, typicalVolumeMl: 1 },
    dosingRange: { low: "250mcg", medium: "500mcg", high: "1mg", frequency: "Daily" },
    tags: ["healing", "recovery", "gut", "angiogenesis", "anti-inflammatory", "tendon", "arginine"],
    sourcingNotes: "Penguin Peptides carries both acetate and arginine forms. Arginine salt preferred for reconstitution stability.",
    warnings: ["Same angiogenesis caveat — avoid with active malignancy", "Oral for gut targeting, subQ for systemic"],
    tier: "entry",
    variantOf: "bpc-157",
    variantNote: "Arginine salt form. More soluble in water and more stable in solution than standard acetate form. Otherwise identical mechanism.",
  },
  {
    id: "wolverine-blend",
    name: "Wolverine Blend",
    aliases: ["Wolverine", "BPC+TB Blend"],
    category: ["Healing / Recovery"],
    mechanism:
      "BPC-157 + TB-500 combination targeting complementary healing pathways. BPC-157 drives angiogenesis and NO signaling; TB-500 handles actin-binding, cell migration, and systemic anti-inflammation. Together they cover soft tissue, tendon, ligament, and systemic recovery.",
    halfLife: "BPC-157 ~4-6hrs, TB-500 days",
    reconstitution: { solvent: "Bacteriostatic Water", typicalVialMg: 10, typicalVolumeMl: 2 },
    dosingRange: { low: "250/2.5mg", medium: "500/5mg", high: "1000/10mg", frequency: "Daily BPC / Twice weekly TB" },
    tags: ["healing", "recovery", "blend", "BPC-157", "TB-500", "tendon", "anti-inflammatory", "synergy"],
    sourcingNotes:
      "Available pre-blended from multiple vendors. Penguin carries BPC+TB combo. Named 'Wolverine' in the community for rapid recovery association.",
    warnings: ["Same angiogenesis caveat as BPC-157 — avoid with active malignancy", "TB-500 long half-life — don't over-frequency dose"],
    tier: "entry",
  },
  {
    id: "glow",
    name: "GLOW",
    aliases: ["GLOW Blend", "GHK-Cu/TB-500/BPC-157"],
    category: ["Healing / Recovery", "Skin / Hair / Nails", "Longevity"],
    mechanism:
      "3-in-1 regenerative blend: GHK-Cu (50mg) drives collagen synthesis, antioxidant enzyme upregulation, and skin regeneration; TB-500 (10mg) handles cell migration and angiogenesis; BPC-157 (10mg) targets tissue repair, gut healing, and anti-inflammatory action. 70mg total per vial.",
    halfLife: "GHK-Cu ~30min, TB-500 days, BPC-157 ~4-6hrs",
    reconstitution: { solvent: "Bacteriostatic Water", typicalVialMg: 70, typicalVolumeMl: 2 },
    dosingRange: { low: "partial vial", medium: "full vial", high: "full vial", frequency: "Weekly or biweekly" },
    tags: ["healing", "skin", "anti-aging", "collagen", "GHK-Cu", "TB-500", "BPC-157", "regenerative", "blend"],
    sourcingNotes:
      "Penguin Peptides $124/vial. >98% purity. Sister blend to KLOW — GLOW is skin/regen focused (high GHK-Cu), KLOW is gut/inflammation focused (KPV + even split).",
    warnings: ["Same angiogenesis caveat as BPC-157", "High GHK-Cu dose — both topical and subQ viable"],
    tier: "pro",
  },
  {
    id: "glp-1-cs",
    name: "CagriSema",
    aliases: ["GLP-1 C+S", "Semaglutide + Cagrilintide", "CagriSema Blend"],
    category: ["GLP / Metabolic"],
    mechanism:
      "Dual-mechanism obesity research blend: Semaglutide (GLP-1 agonist) reduces appetite and slows gastric emptying; Cagrilintide (long-acting amylin analogue) adds complementary satiety signaling via amylin/CGRP receptors. Novo Nordisk's Phase 3 clinical combination (REDEFINE trials). Synergistic weight reduction exceeding either monotherapy.",
    halfLife: "Semaglutide ~7 days; Cagrilintide ~7 days",
    reconstitution: { solvent: "Bacteriostatic Water", typicalVialMg: 5, typicalVolumeMl: 1 },
    dosingRange: { low: "0.25/0.25mg", medium: "1/1mg", high: "2.4/2.4mg", frequency: "Weekly" },
    tags: ["weight loss", "metabolic", "GLP-1", "amylin", "dual agonist", "satiety", "blend", "Novo Nordisk"],
    sourcingNotes: "Penguin Peptides carries as 'GLP-1 C + GLP-1 S'. Clinical trial combination — significant research demand.",
    warnings: ["Titrate each component separately before combining", "GI side effects additive", "Not for use with other GLP-1 agents"],
    tier: "elite",
  },
  {
    id: "cjc-ipa-combo",
    name: "CJC-1295 No DAC + Ipamorelin",
    aliases: ["CJC/Ipa", "Mod GRF + Ipamorelin", "GH Stack Blend"],
    category: ["GH Peptides"],
    mechanism:
      "Gold standard GH pulse stack: CJC-1295 No DAC (GHRH analogue) triggers the somatotroph to release GH; Ipamorelin (selective GHRP) amplifies pulse magnitude without significant cortisol/prolactin bleed. Mimics natural GH pulsatility. Most popular GH peptide combination in research.",
    halfLife: "CJC No DAC ~30min, Ipamorelin ~2hrs",
    reconstitution: { solvent: "Bacteriostatic Water", typicalVialMg: 10, typicalVolumeMl: 2 },
    dosingRange: { low: "100/100mcg", medium: "200/200mcg", high: "300/300mcg", frequency: "2-3x daily, fasted, pre-sleep" },
    tags: ["GH", "growth hormone", "GHRH", "GHRP", "muscle", "recovery", "anti-aging", "blend", "pulse"],
    sourcingNotes: "Penguin carries as 'CJC no DAC + IPA' pre-blended at $72. Most popular GH peptide stack in the community.",
    warnings: ["Dose pre-sleep for maximal GH release alignment", "Avoid within 2hrs of eating or insulin release", "May cause water retention"],
    tier: "pro",
  },
  {
    id: "cagrilintide",
    name: "Cagrilintide",
    aliases: ["GLP-1 C", "AM833", "Long-acting Amylin"],
    category: ["GLP / Metabolic"],
    mechanism:
      "Long-acting amylin analogue. Activates amylin and CGRP receptors in the hypothalamus and brainstem to reduce appetite and slow gastric emptying via a GLP-1-independent pathway. Used standalone or as the 'C' in CagriSema (Novo Nordisk). Finnrick-tested — 16 samples, avg 6.3.",
    halfLife: "~7 days (weekly dosing)",
    reconstitution: { solvent: "Bacteriostatic Water", typicalVialMg: 5, typicalVolumeMl: 1 },
    dosingRange: { low: "0.25mg", medium: "1mg", high: "2.4mg", frequency: "Weekly" },
    tags: ["weight loss", "metabolic", "amylin", "satiety", "CGRP", "Novo Nordisk", "GLP-1 independent"],
    sourcingNotes: "Penguin carries as standalone 'GLP-1 C'. Finnrick avg 6.3/10 — acceptable. Best used in combination with semaglutide (CagriSema).",
    warnings: ["Titrate slowly", "Nausea and injection site reactions common", "Not for use with other amylin analogues"],
    tier: "elite",
  },
  {
    id: "mazdutide",
    name: "Mazdutide",
    aliases: ["IBI362", "OXM3"],
    category: ["GLP / Metabolic"],
    mechanism:
      "GLP-1/glucagon dual receptor agonist developed by Innovent Biologics (China). Glucagon co-agonism increases energy expenditure and hepatic fat metabolism beyond GLP-1 alone. Phase 3 trials in China for obesity and T2D. Finnrick-tested — 10 samples, avg 6.6.",
    halfLife: "~7 days (weekly dosing)",
    reconstitution: { solvent: "Bacteriostatic Water", typicalVialMg: 5, typicalVolumeMl: 1 },
    dosingRange: { low: "1mg", medium: "3mg", high: "9mg", frequency: "Weekly" },
    tags: ["weight loss", "metabolic", "GLP-1", "glucagon", "dual agonist", "liver", "energy expenditure"],
    sourcingNotes: "Finnrick-verified. Chinese-origin compound gaining Western research market traction. Vendor availability growing.",
    warnings: ["Less clinical data available than semaglutide/tirzepatide", "Titrate slowly", "Glucagon agonism may cause nausea"],
    tier: "elite",
  },
  {
    id: "survodutide",
    name: "Survodutide",
    aliases: ["BI 456906", "Boehringer GLP-1/Gcg"],
    category: ["GLP / Metabolic"],
    mechanism:
      "GLP-1/glucagon dual receptor agonist by Boehringer Ingelheim. Phase 3 trials for obesity and MASH (metabolic-associated steatohepatitis). Glucagon component drives hepatic fat clearance — particularly promising for fatty liver research. Finnrick-tested — 7 samples, avg 6.7.",
    halfLife: "~7 days",
    reconstitution: { solvent: "Bacteriostatic Water", typicalVialMg: 5, typicalVolumeMl: 1 },
    dosingRange: { low: "0.6mg", medium: "2.4mg", high: "4.8mg", frequency: "Weekly" },
    tags: ["weight loss", "metabolic", "GLP-1", "glucagon", "dual agonist", "MASH", "fatty liver", "Boehringer"],
    sourcingNotes: "Finnrick avg 6.7/10. Phase 3 compound — strong institutional research demand. Growing vendor availability.",
    warnings: ["Limited long-term safety data", "Hepatic monitoring recommended for MASH applications", "Titrate slowly"],
    tier: "elite",
  },
  {
    id: "orforglipron",
    name: "Orforglipron",
    aliases: ["LY3502970", "Oral GLP-1"],
    category: ["GLP / Metabolic"],
    route: ["oral"],
    mechanism:
      "First oral non-peptide GLP-1 receptor agonist (Eli Lilly). Small molecule — no injection required. Phase 3 trials showing weight loss comparable to injectable GLP-1 agents. Eliminates cold chain storage, reconstitution, and injection entirely. Category-defining compound.",
    halfLife: "~12 hours (twice-daily or daily dosing)",
    reconstitution: { solvent: "N/A — oral capsule/tablet", typicalVialMg: null, typicalVolumeMl: null },
    dosingRange: { low: "3mg", medium: "12mg", high: "36mg", frequency: "Daily oral" },
    tags: ["weight loss", "metabolic", "GLP-1", "oral", "small molecule", "non-peptide", "Eli Lilly", "no injection"],
    sourcingNotes:
      "Swiss Chems carries. No reconstitution needed — oral capsule. Game-changer for accessibility. Not technically a peptide but category-defining for GLP-1 research.",
    warnings: [
      "GI side effects (nausea, diarrhea) common during titration",
      "Not for use with other GLP-1 agents",
      "Small molecule — different sourcing QC applies vs peptide vendors",
    ],
    tier: "pro",
  },
];
