export const BATCH4 = [
  {
    id: "eutropoflavin",
    name: "Eutropoflavin",
    aliases: ["4'-DMA-7,8-DHF", "TrkB Superagonist"],
    category: ["Nootropic", "Longevity"],
    mechanism:
      "Synthetic dimethylamino derivative of 7,8-Dihydroxyflavone. Full TrkB (BDNF receptor) agonist — significantly more potent and bioavailable than 7,8-DHF. Activates BDNF signaling cascade: synaptic plasticity, neurogenesis, neuroprotection. Synergistic with Dihexa (HGF/c-Met pathway). Estimated 7-10x more potent than parent compound.",
    halfLife: "~4-6 hours",
    reconstitution: { solvent: "DMSO or ethanol solution", typicalVialMg: null, typicalVolumeMl: null },
    dosingRange: { low: "5mg", medium: "10mg", high: "15mg", frequency: "Daily oral" },
    tags: ["BDNF", "TrkB", "nootropic", "neurogenesis", "synaptic plasticity", "cognitive", "longevity"],
    sourcingNotes: "Swiss Chems carries as '4'-DMA-7,8-DHF'. Dan's stack: EOD with Dihexa for synergistic HGF+BDNF pathway coverage.",
    warnings: [
      "Very limited human data",
      "Potent TrkB agonism — theoretical oncogenic risk with chronic use (same concern as BDNF)",
      "Oral — DMSO carrier may irritate GI",
    ],
    tier: "elite",
  },
  {
    id: "78-dhf",
    name: "7,8-Dihydroxyflavone",
    aliases: ["7,8-DHF", "TrkB Agonist Flavone"],
    category: ["Nootropic", "Longevity"],
    mechanism:
      "Natural flavone and TrkB (BDNF receptor) agonist. First identified small molecule that crosses the BBB and mimics BDNF at TrkB. Less potent than Eutropoflavin but better characterized. Activates downstream PI3K/Akt and MAPK/ERK pathways for neuroplasticity and neuroprotection.",
    halfLife: "~2-4 hours",
    reconstitution: { solvent: "DMSO or ethanol for solubility; oral powder possible", typicalVialMg: null, typicalVolumeMl: null },
    dosingRange: { low: "25mg", medium: "50mg", high: "100mg", frequency: "Daily oral" },
    tags: ["BDNF", "TrkB", "nootropic", "neurogenesis", "flavone", "neuroprotective", "cognitive"],
    sourcingNotes: "Swiss Chems carries both capsule and powder forms. Precursor/lower-potency alternative to Eutropoflavin.",
    warnings: ["Lower bioavailability than Eutropoflavin — higher doses required", "Theoretical long-term TrkB agonism concerns"],
    tier: "pro",
    variantOf: "eutropoflavin",
    variantNote: "Parent compound. Less potent, lower cost, more characterized. Eutropoflavin is the optimized synthetic derivative.",
  },
  {
    id: "c60-fullerene",
    name: "C60 Fullerene",
    aliases: ["Buckminsterfullerene", "Carbon-60", "ESS60"],
    category: ["Longevity"],
    mechanism:
      "Spherical carbon allotrope with potent radical-scavenging antioxidant properties. Animal studies (Baati 2012 rat study) showed dramatic lifespan extension. Mechanism: accumulates in mitochondrial membranes, neutralizes superoxide and hydroxyl radicals without being consumed. Controversial but has genuine rodent longevity data.",
    halfLife: "Retained in adipose for months",
    reconstitution: { solvent: "Olive oil or MCT oil (lipophilic)", typicalVialMg: null, typicalVolumeMl: null },
    dosingRange: { low: "0.5mg", medium: "1mg", high: "1.5mg", frequency: "Daily in carrier oil" },
    tags: ["antioxidant", "mitochondrial", "longevity", "radical scavenger", "carbon", "lifespan"],
    sourcingNotes: "Swiss Chems carries 1.5mg/mL solution. Must be suspended in oil — not water soluble. High lipophilicity means long tissue retention.",
    warnings: [
      "Very limited human data — extrapolated from rodent studies",
      "Long tissue half-life — dosing conservatively advised",
      "Not technically a peptide — longevity mechanism only",
    ],
    tier: "elite",
  },
  {
    id: "ftpp",
    name: "FTPP (Adipotide)",
    aliases: ["CKGGRAKDC-GG-D(KLAKLAK)2", "Fat-targeted Proapoptotic Peptide"],
    category: ["GLP / Metabolic"],
    mechanism:
      "Proapoptotic peptide that selectively targets vasculature of white adipose tissue. Binds prohibitin on fat cell blood vessels, triggering programmed cell death of adipocytes via a mitochondrial apoptosis cascade. Studied in non-human primates — showed significant fat loss without muscle loss or metabolic disruption.",
    halfLife: "Short — hours",
    reconstitution: { solvent: "Bacteriostatic Water", typicalVialMg: 5, typicalVolumeMl: 1 },
    dosingRange: { low: "1mg/kg", medium: "1mg/kg", high: "1mg/kg", frequency: "Daily x 28-day course" },
    tags: ["fat loss", "adipose", "apoptosis", "metabolic", "body composition", "prohibitin"],
    sourcingNotes: "Swiss Chems carries 5mg. Primate data only — no human trials completed. Highly experimental. Significant renal stress observed in primate studies.",
    warnings: [
      "Significant renal toxicity observed in primate studies — monitor creatinine/GFR",
      "Course protocol only",
      "Most experimental compound on the platform",
      "Dehydration must be avoided",
    ],
    tier: "goat",
  },
  {
    id: "trevogrumab",
    name: "Trevogrumab",
    aliases: ["REGN2477", "Myostatin Antibody"],
    category: ["GH Peptides", "Longevity"],
    mechanism:
      "Fully human monoclonal antibody targeting myostatin (GDF-8). Blocks myostatin from binding its receptor — similar endpoint to follistatin/ACE-031 but via antibody mechanism. Regeneron Phase 2 trials for sarcopenia. Long half-life typical of IgG antibodies.",
    halfLife: "~21 days (typical IgG half-life)",
    reconstitution: { solvent: "Provided in solution — do not reconstitute", typicalVialMg: 1, typicalVolumeMl: 1 },
    dosingRange: { low: "1mg/kg", medium: "3mg/kg", high: "3mg/kg", frequency: "Monthly injection" },
    tags: ["myostatin", "antibody", "muscle", "sarcopenia", "longevity", "hypertrophy", "Regeneron"],
    sourcingNotes: "Swiss Chems carries 1mg vials. Monoclonal antibody — more stable than peptide follistatin. Monthly dosing convenience.",
    warnings: [
      "Monoclonal antibody — immunogenicity possible with repeated use",
      "Limited long-term human data outside clinical trials",
      "Cold chain storage critical",
    ],
    tier: "goat",
  },
  {
    id: "os-01",
    name: "OS-01",
    aliases: ["OneSkin Peptide", "Longevity Topical Peptide"],
    category: ["Skin / Hair / Nails", "Longevity"],
    mechanism:
      "Proprietary peptide developed by OneSkin targeting p21 senescent cells in skin. Reduces senescent cell accumulation, improves skin barrier function, collagen production, and reverses molecular skin aging markers. AI-discovered peptide with published peer-reviewed validation.",
    halfLife: "Topical — tissue residence",
    reconstitution: { solvent: "Topical formulation — no reconstitution", typicalVialMg: null, typicalVolumeMl: null },
    dosingRange: { low: "topical application", medium: "topical application", high: "topical application", frequency: "Daily topical" },
    tags: ["skin", "senolytic", "anti-aging", "topical", "collagen", "longevity", "senescent cells"],
    sourcingNotes:
      "OneSkin brand product — not a research vendor compound. Available direct from OneSkin. AI-discovered and peer-reviewed — notable credibility vs most cosmetic peptides.",
    warnings: ["Topical only — not for injection", "Proprietary formulation — third-party purity testing not available"],
    tier: "pro",
  },
  {
    id: "9-me-bc",
    name: "9-Me-BC",
    aliases: ["9-Methyl-β-carboline", "9MBC"],
    category: ["Nootropic"],
    mechanism:
      "β-carboline alkaloid with potent dopaminergic neurogenesis activity. Stimulates dopamine synthesis, protects dopaminergic neurons, and promotes dendritic growth. Mechanistically distinct from dopamine releasers or reuptake inhibitors — promotes new neuron growth and protection. Stack synergy with Bromantane.",
    halfLife: "Unknown — likely moderate",
    reconstitution: { solvent: "DMSO or ethanol (poorly water soluble)", typicalVialMg: null, typicalVolumeMl: null },
    dosingRange: { low: "5mg", medium: "15mg", high: "25mg", frequency: "Daily oral or sublingual" },
    tags: ["nootropic", "dopamine", "neurogenesis", "neuroprotective", "β-carboline", "cognitive", "motivation"],
    sourcingNotes:
      "Swiss Chems carries caps and powder. Finnrick does not test — research community COAs and reports are the best quality signal. Light-sensitive compound.",
    warnings: ["Light sensitive — store in dark container", "MAO-B inhibitory activity — avoid with tyramine-rich foods at high doses", "Limited human safety data", "Not for those on SSRIs/MAOIs"],
    tier: "elite",
  },
  {
    id: "noopept",
    name: "Noopept",
    aliases: ["Omberacetam", "GVS-111", "N-phenylacetyl-L-prolylglycine ethyl ester"],
    category: ["Nootropic"],
    mechanism:
      "Dipeptide-derived cognitive enhancer. Metabolizes to cycloprolylglycine — an endogenous neuropeptide. Upregulates BDNF and NGF, enhances acetylcholine and glutamate neurotransmission, and has anxiolytic properties at lower doses. ~1000x more potent than piracetam by dose.",
    halfLife: "~15-20 minutes (active metabolite longer)",
    reconstitution: { solvent: "Water soluble — oral or subQ", typicalVialMg: null, typicalVolumeMl: null },
    dosingRange: { low: "5mg", medium: "20mg", high: "30mg", frequency: "1-2x daily" },
    tags: ["nootropic", "BDNF", "NGF", "acetylcholine", "glutamate", "cognitive", "racetam-adjacent"],
    sourcingNotes: "Swiss Chems carries caps and powder. One of the most well-characterized smart drugs. Widely available.",
    warnings: ["Headache at high doses — choline supplementation may help", "Tolerance develops — cycle on/off", "Mild psychostimulant at higher doses"],
    tier: "entry",
  },
  {
    id: "nsi-189",
    name: "NSI-189",
    aliases: ["NSI-189 Phosphate", "Neuralstem compound"],
    category: ["Nootropic"],
    mechanism:
      "Synthetic aminopyridine compound (not a peptide) that stimulates neurogenesis specifically in the hippocampus — increasing hippocampal volume. Phase 2 trials for major depression and cognitive decline. Unique mechanism: expands the hippocampal neural progenitor cell pool. Emotional blunting at high doses — user reports nuanced.",
    halfLife: "~6-12 hours",
    reconstitution: { solvent: "Oral — water soluble phosphate salt", typicalVialMg: null, typicalVolumeMl: null },
    dosingRange: { low: "20mg", medium: "40mg", high: "80mg", frequency: "Daily oral" },
    tags: ["nootropic", "neurogenesis", "hippocampus", "depression", "cognitive", "neural progenitor"],
    sourcingNotes: "Swiss Chems carries caps and powder. Free base and phosphate salt forms — phosphate preferred for stability.",
    warnings: ["Emotional blunting reported at high doses (>40mg)", "Cycle — continuous use data limited", "Not technically a peptide — mechanism is unique enough to earn catalog inclusion"],
    tier: "pro",
  },
  {
    id: "phenibut",
    name: "Phenibut",
    aliases: ["β-Phenyl-GABA", "PhGABA", "Fenibut"],
    category: ["Nootropic", "Sleep"],
    mechanism:
      "GABA-B receptor agonist and partial GABA-A modulator with phenyl ring addition enabling CNS penetration that plain GABA cannot achieve. Produces anxiolytic, mild euphoric, and sleep-promoting effects. Approved pharmaceutical in Russia. High tolerance development and dependence potential — protocol discipline critical.",
    halfLife: "~5-6 hours (effects longer)",
    reconstitution: { solvent: "Oral — HCL or FAA salt", typicalVialMg: null, typicalVolumeMl: null },
    dosingRange: { low: "250mg", medium: "500mg", high: "1000mg", frequency: "1-2x per week maximum" },
    tags: ["GABA", "anxiolytic", "sleep", "social anxiety", "nootropic", "Russian", "phenyl-GABA"],
    sourcingNotes: "Swiss Chems carries HCL and Free Amino Acid (FAA) forms. FAA form less harsh on stomach. Widely used in biohacking community.",
    warnings: [
      "HIGH TOLERANCE AND DEPENDENCE RISK — strictly limit to 1-2x per week",
      "Withdrawal can be severe — do not use daily",
      "Potentiates alcohol and other CNS depressants",
      "Not for anxious or addictive personality profiles without physician oversight",
    ],
    tier: "pro",
  },
  {
    id: "bam-15",
    name: "BAM-15",
    aliases: ["BAM15", "Mitochondrial Uncoupler"],
    category: ["GLP / Metabolic", "Longevity"],
    mechanism:
      "Protonophore mitochondrial uncoupler. Dissipates the proton gradient across the inner mitochondrial membrane as heat rather than ATP — forcing increased substrate oxidation (fat burning) without affecting membrane potential. Animal studies show fat loss without muscle loss, improved insulin sensitivity, and no hyperthermia at research doses. Different mechanism than DNP (far safer profile).",
    halfLife: "Short — hours",
    reconstitution: { solvent: "DMSO solution", typicalVialMg: null, typicalVolumeMl: null },
    dosingRange: { low: "5mg/kg", medium: "5mg/kg", high: "5mg/kg", frequency: "Daily (rodent dosing — human extrapolation TBD)" },
    tags: ["metabolic", "fat loss", "mitochondrial", "uncoupler", "insulin sensitivity", "body composition"],
    sourcingNotes: "Swiss Chems carries. No human trials. Rodent data very promising. Mechanism is legitimate — question is human dose translation.",
    warnings: [
      "No human safety data — rodent studies only",
      "Do NOT confuse with DNP (2,4-dinitrophenol) — different compound, safer profile but still experimental",
      "Hyperthermia theoretically possible at overdose",
    ],
    tier: "goat",
  },
  {
    id: "methylene-blue",
    name: "Methylene Blue",
    aliases: ["MB", "methylthioninium chloride"],
    category: ["Nootropic", "Mitochondrial"],
    mechanism:
      "Mitochondrial electron carrier and MAO inhibitor. Enhances cytochrome c oxidase activity, improves cellular respiration, and has neuroprotective and antioxidant properties at low doses.",
    halfLife: "~5–6 hours",
    reconstitution: { solvent: "Bacteriostatic Water or sterile saline", typicalVialMg: 50, typicalVolumeMl: 10 },
    dosingRange: {
      low: "0.5–1 mg/kg",
      medium: "1–2 mg/kg",
      high: "4 mg/kg (diminishing returns above this)",
      frequency: "Morning only — before noon",
    },
    route: ["oral", "subQ injection", "IV (clinical)"],
    benefits: [
      "Mitochondrial electron transport enhancement",
      "Neuroprotection and cognitive support",
      "Antioxidant at low doses",
      "Mood support via MAO inhibition",
      "Potential Alzheimer's and dementia research applications",
    ],
    sideEffects: [
      "Urine and stool discoloration (blue/green — harmless)",
      "MAO inhibition — avoid with serotonergic compounds",
      "Stimulating — avoid afternoon/night use",
      "Avoid with SSRIs, SNRIs, tramadol (serotonin syndrome risk)",
      "Harmless blue skin tint at higher doses",
    ],
    warnings: [
      "MAO inhibitor — serious interactions with serotonergic drugs",
      "Morning only — stimulating effect disrupts sleep",
      "Do not combine with SSRIs, SNRIs, or tramadol",
      "G6PD deficiency contraindication",
    ],
    stacksWith: ["mots-c", "nad-plus", "ss-31", "bromantane"],
    cycle: "Daily or 5 days on / 2 days off",
    storage: "Room temperature, protect from light",
    notes:
      "Low dose (0.5–2 mg/kg) is the sweet spot — hormetic compound where less is more. High doses are pro-oxidant. Turns urine blue. This is expected and harmless. Walter White got into the wrong chemistry. Stack logged.",
    tags: ["nootropic", "mitochondrial", "cognitive", "neuroprotection", "MAO inhibitor"],
    stabilityDays: 365,
    stabilityNote: "Stable long-term at room temperature. Protect from light.",
  },
  {
    id: "pramipexole",
    name: "Pramipexole",
    aliases: ["Prami", "Mirapex"],
    category: ["Testosterone Support"],
    mechanism:
      "D2/D3 dopamine receptor agonist. FDA-approved for Parkinson's and Restless Legs Syndrome. Used in performance community to: lower prolactin (counteracts prolactin elevation from GHRPs), improve sleep quality and REM, and enhance dopaminergic tone. Micro-dosing for sleep and prolactin management.",
    halfLife: "~8-12 hours",
    reconstitution: { solvent: "Oral capsule", typicalVialMg: null, typicalVolumeMl: null },
    dosingRange: { low: "0.125mg", medium: "0.25mg", high: "0.5mg", frequency: "Nightly (for sleep/prolactin)" },
    tags: ["dopamine", "prolactin", "sleep", "REM", "D2/D3 agonist", "protocol support", "GHRP ancillary"],
    sourcingNotes: "Swiss Chems carries. FDA-approved pharmaceutical. Micro-dose nightly for sleep and prolactin management alongside GH peptide protocols.",
    warnings: [
      "Compulsive behavior reports at higher doses (gambling, hypersexuality) — rare at microdoses",
      "Orthostatic hypotension — rise slowly",
      "Nausea common when starting — take with food",
    ],
    tier: "elite",
  },
];
